services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile-local
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
    ports:
      - 80:5173
    command: "npm run dev-host"