services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile-local
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '80:80'
