version: '3.9'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./certs:/etc/nginx/ssl
      - ../:/var/www/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    container_name: anime_nginx

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - ../:/var/www/
    depends_on:
      - db
    container_name: anime_app

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ../tmp/db:/var/lib/mysql
    env_file:
      - ../.env
    ports:
      - "3307:3306"
    container_name: anime_db
