services:
  app:
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    environment:
      - NODE_ENV=production
    volumes:
      - ../dist:/app/dist
    command: sh -c "npm run build"

  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../dist:/usr/share/nginx/html
    depends_on:
      - app
