# prod
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../dist:/app/dist
    command: "npm run build"

  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../dist:/usr/share/nginx/html
    depends_on:
      - app