version: '3.9'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ../docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ../docker/certs:/etc/nginx/ssl
      - ../:/var/www/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    container_name: anime_nginx

  app:
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
    volumes:
      - ../:/var/www/
    depends_on:
      - db
    container_name: anime_app

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ../tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    container_name: anime_db
