name: Deploy to Server

on:
  push:
    branches:
      - main
env:
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SERVER_IP: ${{ secrets.SERVER_IP }}
  DEPLOY_DIR: /var/www/myanime

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP"
          mkdir -p $DEPLOY_DIR && \
          if [ -d '$DEPLOY_DIR/.git' ]; then
            cd $DEPLOY_DIR && git pull origin main;
          else
            git clone ${{ secrets.REPO_URL }} $DEPLOY_DIR;
          fi"
